### ISSUE TITLE
Invalid block type: Foo\Bar\Block\Baz

### ISSUE THREAD

**Issue by comunidademagento** [markshust/module-foobar#1]
Hello Mark,

See image and erro below.

![captura de tela de 2015-09-15 00 41 54](https://cloud.githubusercontent.com/assets/7476455/9867326/96e147ac-5b42-11e5-8c59-a27c04179385.png)

Invalid block type: Foo\Bar\Block\Baz
#0 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Foo\Bar\Block\B...', Array)
#1 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout/Generator/Block.php(216): Magento\Framework\View\Layout\Generator\Block->createBlock('Foo\Bar\Block\B...', 'content_schedul...', Array)
#2 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout/Generator/Block.php(124): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'content_schedul...')
#3 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#4 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(329): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#5 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#6 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#7 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#8 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#9 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#10 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/View/Layout.php(861): Magento\Framework\View\Layout->build()
#11 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('page_content_he...')
#12 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Cms/Helper/Page.php(171): Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#13 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Cms/Controller/Index/Index.php(43): Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Index\Index\Interceptor), 'home')
#14 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Cms/Controller/Index/Index/Interceptor.php(24): Magento\Cms\Controller\Index\Index->execute(NULL)
#15 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Action/Action.php(103): Magento\Cms\Controller\Index\Index\Interceptor->execute()
#16 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#18 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch', Array)
#19 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'designLoader')
#20 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#23 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'catalog-app-act...')
#24 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Catalog/Model/App/Action/ContextPlugin.php(78): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#25 [internal function]: Magento\Catalog\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#27 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'customer-app-ac...')
#28 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#29 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#31 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'contextPlugin')
#32 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/App/Action/Plugin/Context.php(92): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#33 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#35 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'storeCheck')
#36 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#37 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#39 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'weee-app-action...')
#40 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#41 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#43 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Cms\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'tax-app-action-...')
#44 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Tax/Model/App/Action/ContextPlugin.php(91): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#45 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#47 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#48 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/FrontController.php(45): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#49 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#50 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#51 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#52 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#53 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#54 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#55 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#56 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#57 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#58 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#59 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#60 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#61 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#62 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#63 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#64 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#65 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#66 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#67 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#68 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#69 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#70 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#71 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#72 {main}

**Comment by markshust** [comment]
I believe you may not have added it to app/code/Foo/Bar - is it possible you put the module in a different location or didn't run `./bin/magento module:install Foo_Bar`?

**Comment by markshust** [comment]
Closing for inactivity
